// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"reflect"

	"github.com/stackrox/rox/central/globaldb"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
)

var (
	// CreateTableExternalbackupsStmt holds the create statement for table `externalbackups`.
	CreateTableExternalbackupsStmt = &postgres.CreateStmts{
		Table: `
               create table if not exists externalbackups (
                   Id varchar,
                   serialized bytea,
                   PRIMARY KEY(Id)
               )
               `,
		Indexes:  []string{},
		Children: []*postgres.CreateStmts{},
	}

	// ExternalbackupsSchema is the go schema for table `externalbackups`.
	ExternalbackupsSchema = func() *walker.Schema {
		schema := globaldb.GetSchemaForTable("externalbackups")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.ExternalBackup)(nil)), "externalbackups")
		globaldb.RegisterTable(schema)
		return schema
	}()
)
