// Code generated by pg-bindings generator. DO NOT EDIT.

package schema

import (
	"reflect"

	"github.com/stackrox/rox/central/globaldb"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/pkg/postgres"
	"github.com/stackrox/rox/pkg/postgres/walker"
)

var (
	// CreateTableNetworkpoliciesundodeploymentStmt holds the create statement for table `networkpoliciesundodeployment`.
	CreateTableNetworkpoliciesundodeploymentStmt = &postgres.CreateStmts{
		Table: `
               create table if not exists networkpoliciesundodeployment (
                   DeploymentId varchar,
                   serialized bytea,
                   PRIMARY KEY(DeploymentId)
               )
               `,
		Indexes:  []string{},
		Children: []*postgres.CreateStmts{},
	}

	// NetworkpoliciesundodeploymentSchema is the go schema for table `networkpoliciesundodeployment`.
	NetworkpoliciesundodeploymentSchema = func() *walker.Schema {
		schema := globaldb.GetSchemaForTable("networkpoliciesundodeployment")
		if schema != nil {
			return schema
		}
		schema = walker.Walk(reflect.TypeOf((*storage.NetworkPolicyApplicationUndoDeploymentRecord)(nil)), "networkpoliciesundodeployment")
		globaldb.RegisterTable(schema)
		return schema
	}()
)
